name: flutter_app_base
description: A library which helps managing the dependency container of an application.
version: 1.0.0
repository: https://github.com/wim07101993/flutter_app_base

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ansicolor: ">=2.0.0 <3.0.0"
  auto_route: ^8.1.3
  behaviour: ^3.0.1
  flutter:
    sdk: flutter
  flutter_fox_logging: ^2.0.0
  get_it: ">7.0.0 <=8.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  mocktail:
