name: beaver_dependency_management
description: A library which helps managing the dependency container of an application.
version: 1.0.0
repository: https://github.com/wim07101993/beaver_dependency_management

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  ansicolor: ">=2.0.0 <3.0.0"
  auto_route: ">=7.0.0 <8.0.0"
  behaviour: ">=2.0.0 <3.0.0"
  flutter:
    sdk: flutter
  flutter_fox_logging: ">=1.0.0 <2.0.0"
  get_it: ">7.0.0 <=8.0.0"

dev_dependencies:
  lint:
